### ISSUE TITLE
Impossible to send SCI targets

### ISSUE THREAD

**Issue by agallenne** [JMMC-OpenDev/a2p2#14]
Hello,

I have a visitor run soon and I am trying to send VLTI/PIONIER OBs from Aspro, but it does not work for the SCI targets, while it works for the CALs. I have a popup error window (see attached screenshot), and the following messages in the LOG:

Info message
General error or Absent Parameter in template!
 Missing magnitude or OB not set ?

Error :
 Traceback (most recent call last):
  File "/Users/agallenn/anaconda3/lib/python3.6/site-packages/a2p2/vlti/facility.py", line 97, in processOB
    instrument.submitOB(ob, self.containerInfo)
AttributeError: 'observationConfiguration' object has no attribute 'Target'
 
 Please check LOG and fix before new submission.
Traceback (most recent call last):
  File "/Users/agallenn/anaconda3/lib/python3.6/site-packages/a2p2/vlti/facility.py", line 97, in processOB
    instrument.submitOB(ob, self.containerInfo)
  File "/Users/agallenn/anaconda3/lib/python3.6/site-packages/a2p2/vlti/pionier.py", line 185, in submitOB
    self.checkOB(ob, p2container, False)
  File "/Users/agallenn/anaconda3/lib/python3.6/site-packages/a2p2/vlti/pionier.py", line 56, in checkOB
    folderName = obsconflist[0].Target.name
AttributeError: 'observationConfiguration' object has no attribute 'Target'

I am using a Mac OS 10.12.6 and python 3 from anaconda

[Capture d’écran 2019-05-15 à 17.39.59.pdf](https://github.com/JMMC-OpenDev/a2p2/files/3184566/Capture.d.ecran.2019-05-15.a.17.39.59.pdf)

**Comment by gmella** [comment]
Hi, Ok I catch the bug and will update a new release ASAP.

**Comment by gmella** [comment]
please upgrade a2p2 with  new version (0.2.4) which fixes the issue.
Thx for the feedback.
