### ISSUE TITLE
Dual field issue?

### ISSUE THREAD

**Issue by GillesDuvert** [JMMC-OpenDev/a2p2#16]
Using S Cra B as AO and FT for s C Cra A (1.12 second) distance.

Error :
 Traceback (most recent call last):
  File "/home/gildas/miniconda3/lib/python3.6/site-packages/a2p2/vlti/facility.py", line 97, in processOB
    instrument.submitOB(ob, self.containerInfo)
p2api.P2Error: (400, 'PUT', 'https://www.eso.org/cop/api/v1/obsBlocks/2454075/templates/1672755', 'The value 0.0 entered for parameter SEQ.RELOFF.X is invalid. Expecting a value of type numlist')
 
 Please check LOG and fix before new submission.
Traceback (most recent call last):
  File "/home/gildas/miniconda3/lib/python3.6/site-packages/a2p2/vlti/facility.py", line 97, in processOB
    instrument.submitOB(ob, self.containerInfo)
  File "/home/gildas/miniconda3/lib/python3.6/site-packages/a2p2/vlti/gravity.py", line 247, in submitOB
    self.checkOB(ob, p2container, False)
  File "/home/gildas/miniconda3/lib/python3.6/site-packages/a2p2/vlti/gravity.py", line 239, in checkOB
    DIAMETER, COU_AG_GSSOURCE, GSRA, GSDEC, COU_GS_MAG, dualField, dualFieldDistance, SEQ_FT_ROBJ_NAME, SEQ_FT_ROBJ_MAG, SEQ_FT_ROBJ_DIAMETER, SEQ_FT_ROBJ_VIS, LSTINTERVAL)
  File "/home/gildas/miniconda3/lib/python3.6/site-packages/a2p2/vlti/gravity.py", line 393, in createGravityOB
    tpl, tplVersion = api.setTemplateParams(obId, tpl, values, tplVersion)
  File "/home/gildas/miniconda3/lib/python3.6/site-packages/p2api-0.91-py3.6.egg/p2api.py", line 861, in setTemplateParams
    return self.saveTemplate(obId, template, version)
  File "/home/gildas/miniconda3/lib/python3.6/site-packages/p2api-0.91-py3.6.egg/p2api.py", line 887, in saveTemplate
    return self.put('/obsBlocks/%d/templates/%d' % (obId, template['templateId']), template, etag=version)
  File "/home/gildas/miniconda3/lib/python3.6/site-packages/p2api-0.91-py3.6.egg/p2api.py", line 1313, in put
    return self.request('PUT', url, data, etag)
  File "/home/gildas/miniconda3/lib/python3.6/site-packages/p2api-0.91-py3.6.egg/p2api.py", line 1259, in request
    raise P2Error(r.status_code, method, url, r.json()['error'])
p2api.P2Error: (400, 'PUT', 'https://www.eso.org/cop/api/v1/obsBlocks/2454075/templates/1672755', 'The value 0.0 entered for parameter SEQ.RELOFF.X is invalid. Expecting a value of type numlist')

**Comment by gmella** [comment]
SEQ.RELOFF.X works properly in the last versions
